### PR TITLE
Bug 3547 uwp compatibility

### LINKED ISSUE #3547: UWP client can't connect
I've prepared a sample project based on a self hosted server, a WPF client that works, same code but using a UWP app client on w10 doesn't work, it can't connect. I've checked and granted also permission on the UWP app for internet e private connection, but it still can't connect to the self hosted server. I'm using versione 2.2.0
This scenario is simple to try, can someone please try it and let me know it they can get it working ?
Thanks

I've found other people having troubles with UWP where they cannot resolve dll, 
my problem looks different, the app loads and try to connect but it fails on connect 

any idea ?

### PR DESCRIPTION
**Pull request by bc3tech**
Fixes #3547 (see previous PR request #3591 )

### CODE REVIEW

**Comment by moozzyk** [comment]
@bc3tech It would be awesome if you could rebase this PR on the latest dev and squash. Also, please remove/separate the `nameof` changes - they are not required to fix the UWP issue. 
Last thing - you will need to sign CLA - I am having this setup for this repo. Without a signed CLA we won't be able to merge this change.

**Comment by bc3tech** [comment]
@moozzyk lookin' good now?

**Comment by bc3tech** [comment]
@moozzyk lookin' good now? sorry, not too advanced w/ `git` - let me know if I misunderstood something.

**Comment by bc3tech** [comment]
@moozzyk lookin' good now? sorry, not too advanced w/ `git` - let me know if I misunderstood something.

**Comment by bc3tech** [comment]
@moozzyk any reason this wasn't pulled in before it resulted in conflicts (as i'm seeing today)? I can work to resolve the conflicts unless somebody else will be handling that.

**Comment by moozzyk** [comment]
@bc3tech it was based on master and not on dev and we already have some changes in dev. I rebased it on dev fixed issues with resources and added websocket transport. and this is now part of this PR: https://github.com/SignalR/SignalR/pull/3608 (it's again a bit behind dev)

**Comment by moozzyk** [comment]
Rebased on dev and committed as 4a46099e9323d3be250bc1f013421ffd10a96397

Thanks for your contribution!

**Pull request closed without merging**
