### PR TITLE
Upgrade JQuery to fix CG alerts

### PR DESCRIPTION
**Pull request by wtgodbe**
Update JQuery to 1.9.0

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Yeah, we can't do this... @halter73

**Comment by wtgodbe** [comment]
> Yeah, we can't do this...

Updating to 1.9.0 would fix some, but not all alerts. We'd have to get exemptions for the remaining ones (which are all `Medium` severity), which is possible if we have a good justification

**Comment by wtgodbe** [comment]
Surprisingly enough, the build passed (The only project referencing the `jquery` package directly is `Microsoft.AspNet.SignalR.JS`, which built fine)

**Comment by halter73** [comment]
Forcing an upgrade to multiple major versions of jQuery is *very* risky. jQuery has undergone some big changes since 1.6.4. We do have automated headless-browser-hosted tests and I believe upgrading event to 3.6.0 mostly works, but we've had reports of SignalR breaking with 3.x versions of jQuery on specific platform combinations we do not have automated tests for https://github.com/SignalR/SignalR/issues/4587.

We'd need to invest resources to manually test more client/server combinations in more scenarios before I'd feel comfortable making this kind of change. It's possible updating jQuery is only affecting certain transports on certain browsers, but I'd want to know before forcing an update.

We also don't have any evidence that the way SignalR uses older versions of jQuery is itself insecure. Developers are encouraged to upgrade jQuery to the latest version if that works for their app and use case, but we have to consider that jQuery has a much bigger API surface than this SignalR JS client which hasn't had a major API change in a long time.

If there were a security patch we needed to make to this SignalR JS client, forcing app authors to deal with multiple major versions worth of breaking changes in the jQuery. This would leave a substantial portion of the consumers of this library out in the cold. We have to consider that developers using this library still haven't updated to ASP.NET Core, so we're talking about a lot of legacy apps that haven't been rewritten due to breaking API changes.

**Comment by BrennanConroy** [comment]
Why 1.9 instead of newer 1.x versions?

Also https://github.com/SignalR/SignalR/blob/main/src/Microsoft.AspNet.SignalR.JS/Microsoft.AspNet.SignalR.JS.nuspec#L19 needs updating.

**Comment by wtgodbe** [comment]
> Why 1.9 instead of newer 1.x versions?

1.9.0 is the minimum version to satisfy CG. 1.12.4 was resolved in the package-lock, we could go with that instead.

**Pull request merged**
