### PR TITLE
Fix: contributor license link was broken.

### PR DESCRIPTION
**Pull request by KyleScharnhorst**
Could not sign in with link provided. Searched for solution online and
found cla.microsoft.com to actually work where I could sign in using my
github account.

### CODE REVIEW

**Comment by KyleScharnhorst** [comment]
Not really sure how this contributor license is supposed to work.

This has been labeled cla-not-required. I received an email with a docusign link. Maybe this isn't a fix?

**Comment by KyleScharnhorst** [comment]
updated to use: https://cla2.dotnetfoundation.org

**Comment by moozzyk** [comment]
@KyleScharnhorst - can you fix the description (it contains incorrect link now), rebase and squash?

**Comment by KyleScharnhorst** [comment]
@moozzyk Fixed the link in the commit message.

**Comment by moozzyk** [comment]
Thanks @KyleScharnhorst!

**Pull request merged**
