### PR TITLE
fix #4175 by making TryGetConnectionId virtual

### LINKED ISSUE #4175: [SignalR Service Support] virtualize TryGetConnectionId for PersistentConnection
As per https://github.com/Azure/azure-signalr/pull/159#discussion_r210213550, currently we need to override `connectionToken` with `{connectionId}{userToken}` because there is check inside https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/PersistentConnection.cs#L324. @davidfowl suggests that `TryGetConnectionId` should just be made virtual so that we can avoid parsing the querystring

### PR DESCRIPTION
**Pull request by anurse**
The Azure SignalR Service SDK uses it's own custom connection tokens. Currently, make things work, they manually hack up a connection token that will validate correctly when they pass it through their PersistentConnection. This change allows any PersistentConnection to provide custom `connectionToken` validation and parsing logic by overriding the `TryGetConnectionId` method.

cc @vicancy

Fixes #4175

### CODE REVIEW

**Comment by davidfowl** [comment]
Can you write a test?

**Comment by anurse** [comment]
What do you want to test here? The only change is that it's now virtual when it wasn't before.

**Comment by davidfowl** [comment]
Lets just make sure you can override it and that it gets called.

**Comment by anurse** [comment]
I'm working on a test, but pushed incomplete code so I can work on it at home ;). Will ping when it's ready to review.

**Comment by anurse** [comment]
:up: :date: Ok, tests are in place now.

**Pull request merged**
