### PR TITLE
Fix  jQuery v3.0.0 is unsupported

### PR DESCRIPTION
**Pull request by alextkachuk**
- replace deprecated $().load function to $().ready

#3710

### CODE REVIEW

**Comment by IanYates** [comment]
Confirmed working in my code.  I haven't moved to jQuery 3.0 but was thinking about trying it out soon so you've saved me one headache.  Thanks!

**Comment by dmethvin** [comment]
Note that there can be a big difference between "document ready" which means the HTML document has completely loaded and "window load" which means all resources *inside* the page have loaded as well. The standard way to fix this deprecation is to change `.load(fn)` to `,on("load", fn)` and that's the change I would suggest here.

**Comment by alextkachuk** [comment]
@dmethvin You are right - .load( handler ) is a shortcut for .on( "load", handler ). I changed it.

**Comment by japalo** [comment]
Having the same issue:

```
jquery.js:9612 Uncaught TypeError: url.indexOf is not a function
jQuery.fn.load @ jquery.js:9612
(anonymous function) @ jquery.signalR.js:250
(anonymous function) @ jquery.signalR.js:976
js:18 Uncaught Error: SignalR: SignalR is not loaded. Please ensure jquery.signalR-x.js is referenced before ~/signalr/js.(anonymous function) @ js:18
(anonymous function) @ js:95
```

Is there by any chance possible that you guys update the bower.json dependecy-section from
```
  "dependencies": {
    "jquery": ">=1.6.4"
  }
```
to a working version? As of right now it gets the most recent one i.e. 3.0.0.

**Comment by Compulsed** [comment]
👍

**Comment by moozzyk** [comment]
Thanks for your contribution. I squashed your change and merged into dev as 1feff64b48f611030cfad8827488dbdf6ea91177. It will be included in the 2.2.1 release. 

Next time please run tests and make sure they pass. `.on()` was introduced in version 1.7.0 and the tests were using 1.6.4. While this is a very old version we don't want to make breaking changes like this  in servicing/point releases. The tests also failed when running jquery 3.0.0 due to a breaking change introduced in jquery 3.0.0. I created a follow up commit to sort out these issues.

**Comment by alextkachuk** [comment]
@moozzyk  Good news, thanks!

**Pull request closed without merging**
