### PR TITLE
Add StackExchangeRedis package

### LINKED ISSUE #4230: React to the new StackExchange.Redis v2.0 package
StackExchange released a new Redis library `StackExchange.Redis` V2.0.x

We'll be creating a new package: `Microsoft.AspNet.SignalR.StackExchangeRedis` which uses that. 

cc @anurse @Tratcher @DamianEdwards @Eilon

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes #4230

Things I changed:
- StackExchangeRedis package targets 4.6.1 instead of 4.5
- Changed `bus.SubscribeAsync` to the `channel.OnMessage` usage for preserving message order
- Changed namespace of everything in new package

~~TODO:~~
~~- Localization. Halp!~~

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Do I need to add the package to SignToolData.Satellite.json?

**Comment by anurse** [comment]
You need to add it to both, yes.

**Comment by BrennanConroy** [comment]
Manually verified redis with 2 servers talking to each other

**Comment by ErroneousFatality** [comment]
@BrennanConroy  I'm sorry to ask you this here, but do you by any chance know when will this package be available on Nuget?

**Pull request merged**
