### PR TITLE
Fix license link on github pages

### PR DESCRIPTION
**Pull request by VPashkov**
Despite PR #3768 link to license file is still broken on signalr.net
This PR is an attempt to fix it.

### CODE REVIEW

**Comment by moozzyk** [comment]
@VPashkov - this PR seems to be based on a very old commit (2013). If you sync your branches to the latest you will see that the link is correct. I am closing this PR. Feel free to reopen if you still the issue after you rebased on the latest version of dev branch.

**Comment by VPashkov** [comment]
But link is still broken on [signalr.net](http://signalr.net/). 
When i click to link under "LICENSE" header on [signalr.net](http://signalr.net/) i getting 404 error.

**Comment by moozzyk** [comment]
Looks like signalr.net is reading README from the master branch and changes in dev were not merged to master.

**Comment by moozzyk** [comment]
To add to this. We merge to master after each release. Since the fix was made after 2.2.1 was released it is not in master yet. Next time we ship we will merge changes to master and this will get fixed.

**Comment by VPashkov** [comment]
Got it. Thank you for explanation!

**Pull request closed without merging**
