### PR TITLE
Updating license and license headers

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by moozzyk** [comment]
//cc @Eilon @DamianEdwards Can you take a look - especially at the last commit?

**Comment by Eilon** [comment]
>         <ReplaceWith>https://raw.github.com/SignalR/SignalR/master/LICENSE.md</ReplaceWith>

txt now.

---
Refers to: build/Build.proj:467 in 180a52f. [](commit_id = 180a52f6751f77dccb093f9a259dec860faa8f12, deletion_comment = False)

**Comment by Eilon** [comment]
Looks GREAT! Just one small comment, then :shipit:

**Comment by moozzyk** [comment]
Good catch!

**Pull request merged**
