### PR TITLE
Update public pool name

### PR DESCRIPTION
**Pull request by BrennanConroy**
+@dougbu
Wouldn't let me add you as a reviewer :/

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Hmm, why didn't a build run?

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=1981510&view=results

**Comment by wtgodbe** [comment]
> There was a resource authorization issue: "The pipeline is not valid. Could not find a pool with name NetCore-Public. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

**Comment by alexperovich** [comment]
I think the mps mappings might have gotten horked again for this repo.

**Comment by alexperovich** [comment]
if the azp run triggered a build in dnceng rather than dnceng-public

**Comment by alexperovich** [comment]
Yep, it looks like the mappings are still stuck on dnceng. I will have to work with vsts to get this sorted.

**Comment by alexperovich** [comment]
🥳 it started in the right org

**Comment by alexperovich** [comment]
@BrennanConroy the triggers and reporting are fixed now. There appears to be a test issue though.

**Comment by BrennanConroy** [comment]
Thanks! Do you need permissions anymore? Otherwise I'll remove them.

**Comment by alexperovich** [comment]
This is currently using the old connection type, which doesn't support things like `/azp run`. I will need the permissions until I get the issues with the github app connection resolved.

**Pull request merged**
