### PR TITLE
initial Mac client

### PR DESCRIPTION
**Pull request by tofutim**
I was hoping for Shared library but ended up making links to everything in Client45. It compiles, but I haven't tested yet. Theoretically it would enable WebSockets for Xamarin Mac. Similar strategy could be used to make iOS and Android versions.

### CODE REVIEW

**Comment by tofutim** [comment]
I'm building from Xamarin.Mac from the Mono project. Checking in Visual Studio (Windows), I can compile Android, iOS, tvOS. I cannot load watchOS. And Mac loads but there is a multiple similar errors in building like

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0012	The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	Microsoft.AspNet.SignalR.Client.Mac	D:\Loqu8\Apps\SignalR\src\Microsoft.AspNet.SignalR.Client\Hubs\HubInvocation.cs	13	Active
> 

which seem like Facade issues.

**Comment by tofutim** [comment]
the projects are all compiling, however, build.cmd yields some errors and warnings I haven't been able to figure out. Any insights much appreciated.

**Comment by moozzyk** [comment]
I don't think we will be able to take this. netstandard is the way to go.

**Comment by tofutim** [comment]
you mean netstandard 2.0?

**Comment by moozzyk** [comment]
The lowest that is possible which seems to be netstandard1.3 (1.2 and below do not have `Timer`)

**Comment by tofutim** [comment]
Note that with this approach Sockets would be supported in the Xamarin platforms.

**Comment by moozzyk** [comment]
We decided to cross compile the client for netstandard1.3 which will make the client work on xamarinmac20. ff815cf392e47b331b423e900f2dad72f506ff4e

**Pull request closed without merging**
