### PR TITLE
Preventing pipeline from overriding original callstack ...

### PR DESCRIPTION
**Pull request by pasn**
... when handling exception from server-side hub method.

SignalR is currently sending call stack from "await" in HubPipelineModule.BuildIncoming(). This fix changes this behavior, so that call stack from hub method is not overridden.

### CODE REVIEW

**Comment by davidfowl** [comment]
Why is this a problem? The async state machine is a reality of using async await.

**Comment by pasn** [comment]
The issue is with the CallStack that may be optionally sent from Hub to Client when exception occurs.

I would like the exception to contain the real stack trace and not the internal one from SignalR.

**Comment by pasn** [comment]
Bump.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Pull request closed without merging**
