### PR TITLE
Fixes #3547: uwp compatibility

### LINKED ISSUE #3547: UWP client can't connect
I've prepared a sample project based on a self hosted server, a WPF client that works, same code but using a UWP app client on w10 doesn't work, it can't connect. I've checked and granted also permission on the UWP app for internet e private connection, but it still can't connect to the self hosted server. I'm using versione 2.2.0
This scenario is simple to try, can someone please try it and let me know it they can get it working ?
Thanks

I've found other people having troubles with UWP where they cannot resolve dll, 
my problem looks different, the app loads and try to connect but it fails on connect 

any idea ?

### PR DESCRIPTION
**Pull request by bc3tech**
Fixes #3547 by creating a new UWP lib that uses the same code as the WinRT one. Verified behavior is correct when compiled for .Net Native w/in a UWP project.

### CODE REVIEW

**Comment by mteper** [comment]
:+1: Thank you! Do you build and then copy the dll into your project?

I guess to make this PR complete, the new project should probably be integrated into the build?

**Comment by mteper** [comment]
Also, this PR is not likely to get pulled it since it's submitted against the wrong branch. From Contributing.md:
> Our workflow is loosely based on Github Flow. We actively develop in the dev branch. This means that all pull requests by contributors need to be developed and submitted to the dev branch.

**Comment by bc3tech** [comment]
@mteper yes, it's currently working perfectly in a UWP project live in the Windows Store on both Mobile and Big Windows.

I'll re-submit my PR shortly. Sorry for the confusion.

**Comment by mveroukis** [comment]
So I pulled this branch, built the entire solution in Release mode | Any CPU. When I attempt to add a reference to it from my project (Windows 10 UWP) I get the following: 
A Reference to '...\SignalR\src\Microsoft.AspNet.SignalR.Client\bin\Release\Microsoft.AspNet.SignalR.Client.dll' could not be added. The project targets '.NETCore' while the file reference targets '.NETFramework'. This is not a supported scenario.

Anyway how I can get around this? WHen I added this project via NuGet it seemed to work fine in Debug mode.

**Comment by moozzyk** [comment]
@mveroukis - can you try this branch: bug-3547-websockets ? It has some additional fixes to the PR proposed by @bc3tech and also support for the websocket transport.
Pull and then from VS 2015 Command prompt run `msbuild build\build.proj /t:BuildPackages` - this should give you NuGet packages in the artifacts folder. Then try installing the package to your project.

**Comment by mveroukis** [comment]
I don't see any branch by that name. However, I did get past my issue above when I realized that what I wanted was the Microsoft.AspNet.SignalR.Client.Store project. The portable one might work as well though, maybe I should try that.

**Comment by moozzyk** [comment]
@mveroukis - here is the branch https://github.com/SignalR/SignalR/tree/bug-3547-websockets 
I don't believe the Store client will work on UWP. You will be able to install it but it won't work - you will see something like described in #3547.

**Comment by mveroukis** [comment]
Thanks, I will look into that.

**Comment by bc3tech** [comment]
@moozzyk is correct, the Store client won't work which is why this PR (and subsequently #3597) was submitted.

**Pull request closed without merging**
